- name: Install Java
  apt:
    name: "{{ java_package }}"
    state: present
    update_cache: yes

- name: Create minecraft group
  group:
    name: "{{ minecraft_group }}"

- name: Create minecraft user
  user:
    name: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    shell: /usr/sbin/nologin
    home: "{{ minecraft_home }}"
    create_home: true

- name: Create server directories
  file:
    path: "{{ minecraft_home }}/{{ item }}"
    state: directory
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: '0755'
  loop:
    - ""
    - mods
    - config
    - logs
    - world

- name: Download Forge installer
  get_url:
    url: "{{ forge_installer_url }}"
    dest: "{{ minecraft_home }}/forge-installer.jar"
    mode: '0644'
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"

- name: Run Forge installer
  become_user: "{{ minecraft_user }}"
  shell: >
    java -jar forge-installer.jar --installServer
  args:
    chdir: "{{ minecraft_home }}"
  creates: "{{ minecraft_home }}/forge-{{ minecraft_version }}-universal.jar"

- name: Accept EULA
  template:
    src: eula.txt.j2
    dest: "{{ minecraft_home }}/eula.txt"
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
    mode: '0644'

- name: Download mods
  get_url:
    url: "{{ item.url }}"
    dest: "{{ minecraft_home }}/{{ item.dest }}"
    mode: '0644'
    owner: "{{ minecraft_user }}"
    group: "{{ minecraft_group }}"
  loop: "{{ mods }}"

- name: Deploy systemd service
  template:
    src: minecraft.service.j2
    dest: /etc/systemd/system/minecraft.service
    mode: '0644'
  notify: Restart Minecraft

- name: Enable and start service
  systemd:
    name: minecraft
    enabled: yes
    state: started

- name: Include log cleanup tasks
  include_tasks: log_cleanup.yml
