galaxy_info:
  author: Vladimir Ryadovoy
  description: Install Minecraft server with IndustrialCraft mod
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
